# Node.js with Angular
# Build a project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: CmdLine@2
  inputs:
    script: 'npm i -g @angular/cli'
  displayName: 'Install Angular CLI'

- task: BatchScript@1
  inputs:
    filename: 'buildplugins.bat'
  displayName: 'Build Plugins'

- task: BatchScript@1
  inputs:
    filename: 'buildcore.bat'
  displayName: 'Build Core'